name: Deploy

on:
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "v*"

env:
  PROJECT_NAME: aircaptain
  API_IMAGE: aircaptain-api
  WEB_IMAGE: aircaptain-web
  API_DOCKERFILE: api/AirCaptain.Api/Dockerfile
  WEB_DOCKERFILE: web/Dockerfile
  REGISTRY: ghcr.io
  BADGE_GIST_ID: 0184962696ef0364be7a3f491133f2f9
  REPO_USER: ewancoder
  CHECK_FETCH_DEPTH: 30
  DOTNET_VERSION: "9.0.x"

jobs:
  check-changes:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      web_changed: ${{ steps.filter.outputs.web }}
      api_changed: ${{ steps.filter.outputs.api }}
      db_changed: ${{ steps.filter.outputs.db }}

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.CHECK_FETCH_DEPTH }}

      - name: Check changes
        id: filter
        run: ./.github/scripts/check-changes.sh web api db
        env:
          PREVIOUS_SHA: ${{ github.event.before }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_API_URL: ${{ github.api_url }}

  generate-todos:
    name: Check TODOs
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check TODOs
        run: ./.github/scripts/list-todos.sh
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      # TODO: Consider adding icon/logo here.
      - name: Create TODOs badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ env.BADGE_GIST_ID }}
          filename: ${{ env.PROJECT_NAME }}-todos-${{ github.ref_name }}.json
          label: TODOs
          message: ${{ env.TODOS_COUNT }}
          color: "#7dcbff"

  test-api:
    name: Test API
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.api_changed == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test API
        uses: ./.github/actions/test-dotnet
        with:
          folder: api
          coverageId: ${{ env.API_IMAGE }}
          gistSecret: ${{ secrets.GIST_SECRET }}

  test-api-mutation:
    name: API mutation testing
    runs-on: ubuntu-latest
    needs: test-api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: API mutation testing
        uses: ./.github/actions/test-dotnet-mutation
        with:
          folder: api

  test-api-sonarqube:
    name: SonarQube static analysis
    runs-on: ubuntu-latest
    needs: test-api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: API Sonar analysis
        uses: ./.github/actions/test-dotnet-sonarqube
        with:
          sonarToken: ${{ secrets.API_SONAR_TOKEN }}

  build-api:
    name: Build API
    runs-on: ubuntu-latest
    needs: test-api
    outputs:
      sha: ${{ steps.save.outputs.sha }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_USER }}/${{ env.API_IMAGE }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=semver,pattern={{raw}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha,format=long,prefix=sha-{{branch}}-

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./api
          file: ${{ env.API_DOCKERFILE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Save SHA tag for deployment
        id: save
        run: |
          SHA_TAG=$(echo "${{ steps.meta.outputs.tags }}" | grep "sha-" | cut -d':' -f2)
          echo "Saving SHA tag: $SHA_TAG"
          echo "sha=$SHA_TAG" >> $GITHUB_OUTPUT

  test-web:
    name: Test Web
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.web_changed == 'true'

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"
          cache-dependency-path: web/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install
        working-directory: web

      - name: Test app
        run: pnpm test --watch=false --browsers=ChromeHeadless --code-coverage
        working-directory: web

      - name: Write coverage report to job summary
        if: "!cancelled()"
        run: |
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat coverage/coverage.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo COVERAGE=$(cat coverage/coverage.txt | grep % | awk -F '[% ]+' '{ sum += $3; count++ } END { print sum/count }') >> $GITHUB_ENV
        working-directory: web

      # TODO: Consider adding icon/logo here.
      - name: Create coverage badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        if: "!cancelled()"
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ env.BADGE_GIST_ID }}
          filename: ${{ env.WEB_IMAGE }}-coverage-${{ github.ref_name }}.json
          label: Web UI Coverage
          message: ${{ env.COVERAGE }}%
          valColorRange: ${{ env.COVERAGE }}
          maxColorRange: 80
          minColorRange: 0

  test-web-mutation:
    name: Web mutation testing
    runs-on: ubuntu-latest
    needs: test-web
    if: false # Disable for now, doesn't work with Angular 20.

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"
          cache-dependency-path: web/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install
        working-directory: web

      - name: Mutation testing
        run: pnpm exec stryker run
        working-directory: web

      # TODO: Consider writing info to summary & badges.
      - name: Upload mutation test results
        uses: actions/upload-artifact@v4
        with:
          name: web-mutation-test-results
          path: web/reports/mutation/mutation.html

  test-web-sonarqube:
    name: SonarQube static analysis
    runs-on: ubuntu-latest
    needs: test-web

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.WEB_SONAR_TOKEN }}
        with:
          projectBaseDir: web

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    needs: test-web
    outputs:
      sha: ${{ steps.save.outputs.sha }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set CONFIG_FILE based on environment
        id: set-config
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "CONFIG_FILE=config.development.ts" >> $GITHUB_ENV
          else
            echo "CONFIG_FILE=config.production.ts" >> $GITHUB_ENV
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_USER }}/${{ env.WEB_IMAGE }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=semver,pattern={{raw}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha,format=long,prefix=sha-{{branch}}-

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./web
          file: ${{ env.WEB_DOCKERFILE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CONFIG_FILE=${{ env.CONFIG_FILE }}

      - name: Save SHA tag for deployment
        id: save
        run: |
          SHA_TAG=$(echo "${{ steps.meta.outputs.tags }}" | grep "sha-" | cut -d':' -f2)
          echo "Saving SHA tag: $SHA_TAG"
          echo "sha=$SHA_TAG" >> $GITHUB_OUTPUT

  # TODO: SCP doesn't delete old files during deployment - fix this.
  deploy:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: [check-changes, build-api, build-web]
    if: |
      false &&
      always() && !cancelled() && !failure() &&
      (github.ref == 'refs/heads/main' || (startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-'))) &&
      (
        needs.check-changes.outputs.api_changed == 'true' ||
        needs.check-changes.outputs.web_changed == 'true' ||
        needs.check-changes.outputs.db_changed == 'true'
      )

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "db,docker-compose.yml,.env.prod"
          target: /tmp/${{ env.PROJECT_NAME }}_prod

      - name: Deploy to DO
        uses: appleboy/ssh-action@v1.2.2
        env:
          DB_CHANGED: ${{ needs.check-changes.outputs.db_changed }}
          API_SHA_TAG: ${{ needs.build-api.outputs.sha }}
          WEB_SHA_TAG: ${{ needs.build-web.outputs.sha }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          DEPLOYMENT_ENVIRONMENT: prod
          DEPLOYMENT_IS_PRODUCTION: true
          IS_SWARM: false
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: DB_CHANGED,API_SHA_TAG,WEB_SHA_TAG,PROJECT_NAME,DEPLOYMENT_ENVIRONMENT,DEPLOYMENT_IS_PRODUCTION,IS_SWARM
          script_path: .github/scripts/deploy.sh

  deploy-swarm:
    name: Deploy Production Swarm
    runs-on: ubuntu-latest
    needs: [check-changes, build-api, build-web]
    if: |
      always() && !cancelled() && !failure() &&
      (github.ref == 'refs/heads/main' || (startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-'))) &&
      (
        needs.check-changes.outputs.api_changed == 'true' ||
        needs.check-changes.outputs.web_changed == 'true' ||
        needs.check-changes.outputs.db_changed == 'true'
      )

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "db,swarm-compose.yml,.env.prod"
          target: /tmp/${{ env.PROJECT_NAME }}_prod

      - name: Deploy to DO
        uses: appleboy/ssh-action@v1.2.2
        env:
          DB_CHANGED: ${{ needs.check-changes.outputs.db_changed }}
          API_SHA_TAG: ${{ needs.build-api.outputs.sha }}
          WEB_SHA_TAG: ${{ needs.build-web.outputs.sha }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          DEPLOYMENT_ENVIRONMENT: prod
          DEPLOYMENT_IS_PRODUCTION: true
          IS_SWARM: true
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: DB_CHANGED,API_SHA_TAG,WEB_SHA_TAG,PROJECT_NAME,DEPLOYMENT_ENVIRONMENT,DEPLOYMENT_IS_PRODUCTION,IS_SWARM
          script_path: .github/scripts/deploy.sh

  deploy-develop:
    name: Deploy Development
    runs-on: ubuntu-latest
    needs: [check-changes, build-api, build-web]
    if: |
      false &&
      always() && !cancelled() && !failure() &&
      github.ref == 'refs/heads/develop' &&
      (
        needs.check-changes.outputs.api_changed == 'true' ||
        needs.check-changes.outputs.web_changed == 'true' ||
        needs.check-changes.outputs.db_changed == 'true'
      )

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USERNAME_DEV }}
          passphrase: ${{ secrets.PASSWORD_DEV }}
          key: ${{ secrets.KEY_DEV }}
          port: ${{ secrets.PORT_DEV }}
          source: "db,docker-compose.yml,.env.dev"
          target: /tmp/${{ env.PROJECT_NAME }}_dev

      - name: Deploy to DEV server
        uses: appleboy/ssh-action@v1.2.2
        env:
          DB_CHANGED: ${{ needs.check-changes.outputs.db_changed }}
          API_SHA_TAG: ${{ needs.build-api.outputs.sha }}
          WEB_SHA_TAG: ${{ needs.build-web.outputs.sha }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          DEPLOYMENT_ENVIRONMENT: dev
          DEPLOYMENT_IS_PRODUCTION: false
          IS_SWARM: false
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USERNAME_DEV }}
          passphrase: ${{ secrets.PASSWORD_DEV }}
          key: ${{ secrets.KEY_DEV }}
          port: ${{ secrets.PORT_DEV }}
          envs: DB_CHANGED,API_SHA_TAG,WEB_SHA_TAG,PROJECT_NAME,DEPLOYMENT_ENVIRONMENT,DEPLOYMENT_IS_PRODUCTION,IS_SWARM
          script_path: .github/scripts/deploy.sh

  deploy-develop-swarm:
    name: Deploy Development Swarm
    runs-on: ubuntu-latest
    needs: [check-changes, build-api, build-web]
    if: |
      true &&
      always() && !cancelled() && !failure() &&
      github.ref == 'refs/heads/develop' &&
      (
        needs.check-changes.outputs.api_changed == 'true' ||
        needs.check-changes.outputs.web_changed == 'true' ||
        needs.check-changes.outputs.db_changed == 'true'
      )

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "db,swarm-compose.yml,.env.dev"
          target: /tmp/${{ env.PROJECT_NAME }}_dev

      - name: Deploy to DEV
        uses: appleboy/ssh-action@v1.2.2
        env:
          DB_CHANGED: ${{ needs.check-changes.outputs.db_changed }}
          API_SHA_TAG: ${{ needs.build-api.outputs.sha }}
          WEB_SHA_TAG: ${{ needs.build-web.outputs.sha }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          DEPLOYMENT_ENVIRONMENT: dev
          DEPLOYMENT_IS_PRODUCTION: false
          IS_SWARM: true
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: DB_CHANGED,API_SHA_TAG,WEB_SHA_TAG,PROJECT_NAME,DEPLOYMENT_ENVIRONMENT,DEPLOYMENT_IS_PRODUCTION,IS_SWARM
          script_path: .github/scripts/deploy.sh
